# Generated by Django 4.1.7 on 2023-03-07 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='guru',
            fields=[
                ('nip', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jk', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('agama', models.CharField(max_length=20)),
                ('no_tlpn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='kelas',
            fields=[
                ('id_kelas', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=255)),
                ('nip_waliKelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.guru')),
            ],
        ),
        migrations.CreateModel(
            name='mapel',
            fields=[
                ('id_mapel', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_maple', models.CharField(max_length=255)),
                ('nip_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.guru')),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('id_user', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='siswa',
            fields=[
                ('nis', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jk', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('agama', models.CharField(max_length=20)),
                ('no_tlpn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('foto', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateTimeField()),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.kelas')),
                ('id_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.user')),
            ],
        ),
        migrations.CreateModel(
            name='nilai',
            fields=[
                ('id_nilai', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nil_ul1', models.IntegerField(max_length=3)),
                ('nil_ul2', models.IntegerField(max_length=3)),
                ('nil_ul3', models.IntegerField(max_length=3)),
                ('nil_uts', models.IntegerField(max_length=3)),
                ('nil_uas', models.IntegerField(max_length=3)),
                ('nil_rata_rata', models.IntegerField(max_length=3)),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.mapel')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.siswa')),
            ],
        ),
        migrations.AddField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.user'),
        ),
    ]
