# Generated by Django 4.1.7 on 2023-05-03 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guru',
            fields=[
                ('nip', models.CharField(max_length=118, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jk', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('agama', models.CharField(max_length=20)),
                ('no_tlpn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/assets/dist/img')),
                ('tgl_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id_kelas', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama_kelas', models.CharField(max_length=255)),
                ('nip_waliKelas', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sins.guru')),
            ],
        ),
        migrations.CreateModel(
            name='Mapel',
            fields=[
                ('id_mapel', models.CharField(max_length=4, primary_key=True, serialize=False)),
                ('nama_mapel', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nis', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=255)),
                ('jk', models.CharField(max_length=10)),
                ('alamat', models.TextField()),
                ('agama', models.CharField(max_length=20)),
                ('semester', models.CharField(max_length=10)),
                ('no_tlpn', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='static/assets/dist/img')),
                ('tgl_lahir', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id_user', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=10)),
                ('role', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa_Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.kelas')),
                ('nis_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.siswa')),
            ],
        ),
        migrations.AddField(
            model_name='siswa',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.user'),
        ),
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nil_uts', models.IntegerField()),
                ('nil_uas', models.IntegerField()),
                ('nil_rata_ul', models.IntegerField()),
                ('nil_rata_tg', models.IntegerField()),
                ('nil_rata_rata', models.IntegerField()),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.mapel')),
                ('id_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.mapel')),
                ('nip_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.guru')),
            ],
        ),
        migrations.AddField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.user'),
        ),
    ]
