# Generated by Django 4.1.7 on 2023-05-04 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_rata',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_tg',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_ul',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uas',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uts',
            field=models.FloatField(default=0.0),
        ),
    ]
