# Generated by Django 4.1.7 on 2023-03-07 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_rata',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uas',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_ul1',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_ul2',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_ul3',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uts',
            field=models.IntegerField(),
        ),
    ]
