# Generated by Django 4.1.7 on 2023-05-04 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0002_alter_nilai_nil_rata_rata_alter_nilai_nil_rata_tg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_rata',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_tg',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_rata_ul',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uas',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='nilai',
            name='nil_uts',
            field=models.FloatField(),
        ),
    ]
