# Generated by Django 4.1.7 on 2023-05-20 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0003_alter_nilai_nil_rata_rata_alter_nilai_nil_rata_tg_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='nip',
            field=models.CharField(max_length=18, primary_key=True, serialize=False),
        ),
    ]
