# Generated by Django 4.1.7 on 2023-03-30 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0005_alter_kelas_nip_walikelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='nip_waliKelas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.guru'),
        ),
    ]
