# Generated by Django 4.1.7 on 2023-03-30 04:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0006_alter_kelas_nip_walikelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sins.user'),
        ),
        migrations.AlterField(
            model_name='kelas',
            name='nip_waliKelas',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sins.guru'),
        ),
    ]
