# Generated by Django 4.1.7 on 2023-03-30 04:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0007_alter_guru_id_user_alter_kelas_nip_walikelas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='id_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.user'),
        ),
    ]
