# Generated by Django 4.1.7 on 2023-03-31 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0008_alter_guru_id_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guru',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/dist/img'),
        ),
    ]
