# Generated by Django 4.1.7 on 2023-04-01 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0009_alter_guru_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id_user',
            field=models.CharField(max_length=5, primary_key=True, serialize=False),
        ),
    ]
