# Generated by Django 4.1.7 on 2023-04-03 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0010_alter_user_id_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mapel',
            name='nip_guru',
        ),
    ]
