# Generated by Django 4.1.7 on 2023-04-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0011_remove_mapel_nip_guru'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mapel',
            old_name='nama_maple',
            new_name='nama_mapel',
        ),
    ]
