# Generated by Django 4.1.7 on 2023-04-06 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0016_remove_mapel_nip_guru'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapel',
            name='nip_guru',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sins.guru'),
            preserve_default=False,
        ),
    ]
