# Generated by Django 4.1.7 on 2023-04-10 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0017_mapel_nip_guru'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ulangan',
            fields=[
                ('id_ulangan', models.CharField(max_length=5, primary_key=True, serialize=False)),
                ('nama_ulangan', models.CharField(max_length=255)),
                ('nilai_ulangan', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.RemoveField(
            model_name='mapel',
            name='nip_guru',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='nil_ul1',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='nil_ul2',
        ),
        migrations.RemoveField(
            model_name='nilai',
            name='nil_ul3',
        ),
        migrations.RemoveField(
            model_name='siswa',
            name='id_kelas',
        ),
        migrations.AddField(
            model_name='siswa',
            name='semester',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siswa',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='static/assets/dist/img'),
        ),
        migrations.CreateModel(
            name='Siswa_Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.kelas')),
                ('nis_siswa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='Jadwal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_kelas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.kelas')),
                ('id_mapel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.mapel')),
                ('nip_guru', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sins.guru')),
            ],
        ),
        migrations.AddField(
            model_name='nilai',
            name='id_ulangan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='sins.ulangan'),
            preserve_default=False,
        ),
    ]
