# Generated by Django 4.1.7 on 2023-04-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0018_ulangan_remove_mapel_nip_guru_remove_nilai_nil_ul1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ulangan',
            name='nilai_ulangan',
            field=models.IntegerField(),
        ),
    ]
