# Generated by Django 4.1.7 on 2023-04-16 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0019_alter_ulangan_nilai_ulangan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='id_kelas',
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
