# Generated by Django 4.1.7 on 2023-05-01 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0021_users_alter_guru_id_user_alter_siswa_id_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
