# Generated by Django 4.1.7 on 2023-05-01 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sins', '0022_remove_users_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
